# Generated by Django 2.0.3 on 2018-03-23 17:51

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('IBAN', localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=True, verbose_name='IBAN NO')),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
    ]
